In [1]:
"""***************************** 22nd April'23 Assignment *****************************"""

"***************************** 22nd April'23 Assignment *****************************"

# KNN-3

#### Q1. Write a Python code to implement the KNN classifier algorithm on load_iris dataset in sklearn.datasets.

In [28]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [29]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
df = load_iris()
X_train,X_test,y_train,y_test=train_test_split(df.data, df.target,test_size=0.33,random_state=42)

In [30]:
from sklearn.neighbors import KNeighborsClassifier
clasifier = KNeighborsClassifier(n_neighbors=5,algorithm='auto')
clasifier.fit(X_train,y_train)
y_pred = clasifier.predict(X_test)

In [31]:
from sklearn.metrics import accuracy_score
print("Accuracy is :",accuracy_score(y_test,y_pred))

Accuracy is : 0.98


#### Q2. Write a Python code to implement the KNN regressor algorithm on load_boston dataset in sklearn.datasets.

In [32]:
#from sklearn.datasets import load_bston
df1 = pd.read_csv("housing.csv")
df1.head()

RM  LSTAT  PTRATIO      MEDV
0  6.575   4.98     15.3  504000.0
1  6.421   9.14     17.8  453600.0
2  7.185   4.03     17.8  728700.0
3  6.998   2.94     18.7  701400.0
4  7.147   5.33     18.7  760200.0

In [33]:
X1 = df1.drop('MEDV', axis=1)
y1 = df1['MEDV']

In [34]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import confusion_matrix
X1_train,X1_test,y1_train,y1_test = train_test_split(X1,y1,random_state=42,test_size=0.2)
clss = KNeighborsRegressor(n_neighbors=10)
clss.fit(X1_train,y1_train)
y1_pred = clss.predict(X1_test)
print("Accuracy : ",accuracy_score(y1_test,y1_pred))
print(confusion_matrix(y1_test,y1_pred))

Accuracy :  0.0
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]]


#### Q3. Write a Python code snippet to find the optimal value of K for the KNN classifier algorithm using cross-validation on load_iris dataset in sklearn.datasets.

In [46]:
from sklearn.model_selection import KFold,cross_val_score
df=load_iris()
lst=[]
ran=range(1,16)
for i in ran:
    clasf = KNeighborsClassifier(n_neighbors=i,algorithm='auto')
    cv = KFold(n_splits=7)
    score = cross_val_score(clasf,df.data,df.target,cv=cv,scoring='accuracy')
    lst.append(score.mean())

result = ran[lst.index(max(lst))]
print("Optimal Value is : ",result)

Optimal Value is :  1


#### Q4. Implement the KNN regressor algorithm with feature scaling on load_boston dataset in sklearn.datasets.

In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("housing.csv")
df.head(2)

RM  LSTAT  PTRATIO      MEDV
0  6.575   4.98     15.3  504000.0
1  6.421   9.14     17.8  453600.0

In [8]:
y=df['MEDV']
X=df.drop('MEDV',axis=1)

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsRegressor
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
clsi = KNeighborsRegressor(n_neighbors=5,algorithm='auto')
clsi.fit(X_train,y_train)
y_pred = clsi.predict(X_test)

In [13]:
from sklearn.metrics import accuracy_score
print("Accuracy is : ",accuracy_score(y_test,y_pred))

Accuracy is :  0.030612244897959183


#### Q5. Write a Python code snippet to implement the KNN classifier algorithm with weighted voting on load_iris dataset in sklearn.datasets.

In [14]:
from sklearn.datasets import load_iris
df = load_iris()
X=df.data
y=df.target

In [15]:
from sklearn.neighbors import KNeighborsClassifier
cl = KNeighborsClassifier(n_neighbors=10,weights='distance')

In [16]:
cl.fit(X,y)
y_pred = cl.predict(X)

In [17]:
print("Pridect data : ",y_pred)

Pridect data :  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


#### Q6. Implement a function to standardise the features before applying KNN classifier.

In [20]:
from sklearn.preprocessing import StandardScaler
def standardise(X):
    scaler = StandardScaler()
    X_std=scaler.fit_transform(X)
    return X_std

X_std = standardise(X)

clss = KNeighborsClassifier(n_neighbors=7,algorithm='auto')
clss.fit(X_std,y)
y_pred = clss.predict(X_std)
print("Prdct data : ",y_pred)

Prdct data :  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1
 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 1 2 2 2 2
 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


#### Q7. Write a Python function to calculate the euclidean distance between two points.

In [32]:
from sklearn.datasets import load_iris
iris = load_iris()
x1=iris.data[0]
x2=iris.data[100]

In [34]:
print(x1,x2)

[5.1 3.5 1.4 0.2] [6.3 3.3 6.  2.5]


In [36]:
import math
def euclidean(x1,x2):
    distance =0
    for i in range(len(x1)):
        distance+=(x1[i]-x2[i])**2
    distance=math.sqrt(distance)
    return distance

res = euclidean(x1,x2)
print("Euclidean Distance is : ",res)

Euclidean Distance is :  5.2848841046895245


#### Q8. Write a Python function to calculate the manhattan distance between two points.

In [39]:
def manhatten(x1,x2):
    dis=0
    for i in range(len(x1)):
        dis+=abs(x1[i]-x2[i])
    return dis
res1=manhatten(x1,x2)
print("Manhatten Distance : ",res1)

Manhatten Distance :  8.3
